### ISSUE TITLE
[BUG] Test code should not assume networkx is installed

### ISSUE THREAD

**Issue by bluescarni** [esa/pygmo2#120]
**Describe the bug**
The test suite assumes that networkx is installed, although networkx is not a mandatory dependency for pygmo.

**To Reproduce**
Install pygmo and run the test suite **without** installing networkx.

**Expected behavior**
The test suite should just skip the tests using networkx, if networkx is not installed.

**Comment by rubenperezm** [comment]
`_algorithm_test.py` also assumes that `scipy` is installed:

```
ERROR: runTest (pygmo._algorithm_test.algorithm_test_case.runTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ruben/aerospace/pygmo2/build/pygmo/_py_algorithms.py", line 351, in __init__
    from scipy.optimize import minimize, NonlinearConstraint
ModuleNotFoundError: No module named 'scipy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ruben/aerospace/pygmo2/build/pygmo/_algorithm_test.py", line 28, in runTest
    self.run_scipy_wrapper_tests()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/ruben/aerospace/pygmo2/build/pygmo/_algorithm_test.py", line 450, in run_scipy_wrapper_tests
    self.assertRaises(ValueError, lambda: scipy_optimize(method="foo"))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ruben/miniconda3/envs/pygmo/lib/python3.13/unittest/case.py", line 795, in assertRaises
    return context.handle('assertRaises', args, kwargs)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ruben/miniconda3/envs/pygmo/lib/python3.13/unittest/case.py", line 238, in handle
    callable_obj(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/ruben/aerospace/pygmo2/build/pygmo/_algorithm_test.py", line 450, in <lambda>
    self.assertRaises(ValueError, lambda: scipy_optimize(method="foo"))
                                          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ruben/aerospace/pygmo2/build/pygmo/_py_algorithms.py", line 354, in __init__
    raise ImportError(
    ...<2 lines>...
    )
ImportError: from scipy.optimize import minimize raised an exception, please make sure scipy is installed and reachable. Error: No module named 'scipy'

----------------------------------------------------------------------
```
